Features page rewrite
mixxxdj/website pull request #10
Opened 2015-12-22 07:44 UTC by Be-ing

Rewrite features page to use more concise and down-to-earth language rather than sensational hype. Also shuffle some content around. Remove "Full specifications" section from already long page and move some information from it to relevant sections

2015-12-22 13:27 UTC, esbrandt commented on pages/features.html
> +      <!--TODO: clarify. What does "optional" mean?-->
Due to licensing reasons we can not bundle the app with mp3 codec, you have to install manually.
no codec installed = no recording/streaming in mp3 format
http://mixxx.org/manual/2.0/chapters/livebroadcasting.html#activate-mp3-streaming-support
https://bugs.launchpad.net/mixxx/+bug/1294128

2015-12-22 13:30 UTC, esbrandt commented on pages/features.html
> +        {% blocktrans with vinyl_control_manual_link="/manual/latest/chapters/vinyl_control.html" %}Serato CV 2, Serato CV 2.5, Traktor Scratch Mk1, and Mixvibes DVS V2 timecode are supported with ab
Good that you link to the manual instead of the wiki here. It provides much more complete information.

2015-12-22 13:38 UTC, esbrandt commented
I generally like the change in tone. Goes well with the proposed frontpage changes.

But why the removed full specs part? Ok, the page is rather long, but how does it matter?
This kind of information is elsewhere often buried in manuals or knowledge base articles, and i found it as some sort of service that we have it at the homepage.

2015-12-22 14:22 UTC, ywwg commented
I appreciate your interest and ideas in changing the tone of the website, and in many cases I agree with the changes.  But at this time I am focused on getting the information and screenshots up to date in time for the release.  Trying to also rewrite the tone but maintain accuracy is an extra burden that  we don't have the bandwidth for right now, so I'd ask that you put this work aside for now.

2015-12-22 14:33 UTC, Be-ing commented
What if @esbrandt and/or @rryan review it?

2015-12-22 14:40 UTC, Be-ing commented
> But why the removed full specs part? Ok, the page is rather long, but how does it matter?
> This kind of information is elsewhere often buried in manuals or knowledge base articles, and i found it as some sort of service that we have it at the homepage.

A long page feels cluttered. The section was three columns of bullet lists, two of which were very long and didn't really add much. The short list of supported timecode vinyls was moved to the vinyl control section. For the list of controllers, the controller section now links to the wiki, which has more information presented in a neater table format than that long bullet list. Most of the info that was in the first column is mentioned elsewhere on the page and/or the front page of the website. I'll take another look through the removed section and look for helpful info that isn't clearly mentioned elsewhere on the frontpage & features page.

2015-12-22 16:58 UTC, Be-ing commented on pages/features.html
> +      <!--TODO: clarify. What does "optional" mean?-->
How about:
"Record your live mixes to the lossless WAVE or compressed Ogg Vorbis formats, with MP3 recording enabled by separate (external?) LAME library"

2015-12-22 17:02 UTC, ywwg commented
RJ and Sean are busy with last-minute code fixes, PPA issues, and other things.  I will look through your PRs for suggestions but I won't be merging them, sorry!

2015-12-22 20:29 UTC, daschuer commented on pages/features.html
> +  {% trans "Essential tools for seemlessly blending music" %}
Essential tools integrated for ..

2015-12-22 20:32 UTC, daschuer commented on pages/features.html
> +      {% trans "Drop a song onto a deck in Mixxx to start playing right away. Each deck features a scratchable, scrolling waveform that marks beats and cue points, along with a whole-song waveform ov
This paragraph changes from a command style to description style. 
Maybe we can continue like "Scratch the track using mouse ...

2015-12-22 20:36 UTC, daschuer commented on pages/features.html
> +      {% trans "Set and trigger up to four hotcues. Our playback engine is finely tuned for accurate, rapid fire hotcue triggering so you can mash and remix as hard as you want to without a hiccup."
The "four" is a skin only limit. Here we have again command style mixed with explanations.

2015-12-22 20:44 UTC, daschuer commented on pages/features.html
> +        {% trans "Filter your collection by specific tags to narrow your choices or just start typing to find the track you're thinking of. Sort the library table hierarchically with multiple tags at
I am afraid we are not that far:
"Sort the library table hierarchically with multiple tags at a time."

2015-12-22 20:46 UTC, Be-ing commented on pages/features.html
> +        {% trans "Filter your collection by specific tags to narrow your choices or just start typing to find the track you're thinking of. Sort the library table hierarchically with multiple tags at
What do you mean? The hierarchical sorting works well.

2015-12-22 20:54 UTC, daschuer commented on pages/features.html
> +        {% trans "Filter your collection by specific tags to narrow your choices or just start typing to find the track you're thinking of. Sort the library table hierarchically with multiple tags at
I have probably misread the sentences since we have no hierarchical tagging system.

2015-12-23 02:37 UTC, Be-ing commented
@daschuer I have changed the language to use more imperative verbs. Thanks for the suggestion.
@esbrandt I restored the info about translations. Other than that, I don't really see the value of keeping the "Full Specifications" section. It was a big wall of text that condensed the info already on the front page and this page but without pretty pictures to break it up.

2015-12-23 12:39 UTC, Be-ing commented
@esbrandt If you think the feature list should come back, I don't feel too strongly either way. However, I think the list of controllers should stay on the wiki so we don't have to keep updating it in multiple places. Without that taking up a column, the page could be shortened by splitting the features into the left and middle columns.

2015-12-23 13:04 UTC, Be-ing commented
@ywwg It is really frustrating that I have been asking about the status of the website and how to contribute to it for months with no response. I only realized that it was hosted on GitHub recently and I could open PRs for the website. It is also frustrating to have to ask about release schedules then be told on only a few days notice, so I've been staying up late all week working on this to leave a little time for review. Two others are reviewing these changes, so I don't understand why you're standing in the way.

2015-12-23 14:04 UTC, rryan commented
@Be-ing -- I understand your frustration and am sorry that hosting it on GitHub gave you the impression we were accepting rewrite PRs. It's hosted on GitHub for version control purposes and to centralize process around i18n and deploying the website. Only those with push access are intended to be making changes.

However, Owen made it clear shortly after you submitted this that it would not be accepted so the guilt tripping is not warranted.

2015-12-23 14:29 UTC, daschuer commented
Why will you not accept PR for our web sides at all? 

This PR might be too late to be merged before release, but it contains some nice improvements, so we should consider to merge it once it is mature.

2017-01-18 21:22 UTC, Be-ing commented
Thoughts about reviving this for the 2.1 release?

2017-02-02 12:51 UTC, esbrandt commented
Still a welcomed change to me, same with the frontpage PR . 
Responsive website sounds good too, as long as it will continue to support i18n ( which will hopefully come live for the next release, infrastructure is in place).

2017-02-02 15:12 UTC, Be-ing commented
How is i18n done? I'm guessing that hooks into Cactus somehow?

2017-02-02 17:22 UTC, esbrandt commented
Basically just wrap the strings, see https://github.com/mixxxdj/website#documentation.

Post merge we can upload the updated translation template to Transifex for translations.
Website translation stubs are on https://www.transifex.com/mixxx-dj-software/mixxxdj-website/.

What has to be done on the servers site to actually serve multi-language pages, @rryan knows probably best

2017-02-06 20:05 UTC, ywwg requested changes
Mostly small notes, but there's some subtlety in the original that I want to restore.

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +      {% trans "Change the tempo of songs without changing their pitch with keylock, or change the pitch apart from tempo so your songs play in harmony. Temporarily nudge the tempo faster or slower f
"apart from tempo" is a bit awkward.  how about: "or change the pitch without breaking sync so your songs play in harmony"

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +      {% trans "Change the tempo of songs without changing their pitch with keylock, or change the pitch apart from tempo so your songs play in harmony. Temporarily nudge the tempo faster or slower f
I'd prefer not to include our buzzword of "ramping pitchbend," which isn't a generic term.  How about "with changes in pitch smoothly applied just like vinyl."

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +      {% trans "Need to extend your mix while you bring in the next track? Loop a 4, 8, or 16 beat segment with ease." %}
I like "instantly" or "one button" because it emphasizes that the DJ doesn't need to set up the loop ahead of time.

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +      {% trans "Set hotcues to mark places in tracks. Remix and mash up tracks with accurate, rapid fire hotcue triggering." %}
"rapid-fire"

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +      {% trans "Compatibile with music files in lossless FLAC, WAV, and AIFF formats as well as lossy MP3, M4A/AAC, Ogg Vorbis, and Opus formats." %}
spelling: Compatible

I don't think it's worth calling out "lossy" vs "lossless", but that's not a big deal

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +      {% trans "Choose between multiple audiophile filters with adjustable EQ shelves. Crossfader curve control lets you deliver quick cuts or long, smooth crossfades." %}
"audiophile-grade" ?

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +      {% trans "Use reverb, echo, flange, and more effects to blend music in your own signature ways. Assign a Quick Effect to your controller's filter knob to add color to your sound instantly.  Bad
Effects are not necessarily about blending, so this change feels meh to me.  They're something added on top, which is why I went with "sizzle."  or: spice

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +    {% trans "Free as in freedom as well as price, Mixxx plays nice with a variety of hardware without artificial restrictions or vendor lock-in mechanisms. The free version is the full version. Pick
I don't like the "free as in freedom" mantra, I'd prefer not to use it.  It's also not quite specific to the hardware support bullet  Maybe:

"Mixxx plays nice with a variety of hardware without artificial restrictions or exclusive vendor tie-ins. Use whatever gear you want to build your unique setup."

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +        {% blocktrans with hardware_compatibility_wiki_link="/wiki/doku.php/hardware_compatibility" %}<b>Included Presets</b><br> for controllers such as the Traktor Kontrol S4 MK2, Pioneer DDJ-SB &a
Add the phrase "fully supported" somewhere :)

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +        {% blocktrans with midi_scripting_wiki_link="/wiki/doku.php/midi_scripting" %}Cutting-edge JavaScript-based scripting engine provides maximum flexibility. MIDI or HID messages can be mapped o
maybe "For advanced users..."   Nearly all of our users just want to click a preset and go, so I want to make sure we call out javascript as a bonus extra, not a standard thing people will interact with

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +        {% blocktrans with vinyl_control_manual_link="/manual/latest/chapters/vinyl_control.html" %}Serato CV 2, Serato CV 2.5, Traktor Scratch Mk1, and Mixvibes DVS V2 timecode are supported with ab
Maybe pull back on the technical stuff and emphasize the physical connection between record and music.   Steve Job's old line of "touch your music" is an example.

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +      {% trans "Stay organized and find the music you're looking for the moment you need it. Powered by a high-performance database, navigation and searching your collection is intuitive and fast." %
I liked the line about how the library is designed by and for DJs, rather than just another music playing app

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +        {% trans "Sort your music the way you want. Use playlists to arrange plans for a set and unordered crates to build your own categorization system." %}
"Use playlists to preplan your set, or use crates to build your own categorization system."

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +        {% trans "Filter your collection by specific tags to narrow your choices or just start typing to find the track you're thinking of. Sort the library table hierarchically with multiple tags at
go through and remove excess incidences of the word "just" -- it's lazy and I do it too, but it sounds cheap

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +      <p class="feature_indent">{% trans "Upgraded BPM detection library does an even better job finding the beat in even the toughest rhythms. New musical key detection provides more information to
don't say new... the website gets out of date quickly and having the word "new" is not really important except when we do our specific "what's new in this version" pages.

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +        <p>{% trans "Three exclusive designer skins with configurable layouts" %}</p>
remove the number in case it changes.

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +        {% trans "Song gain is automatically adjusted when loading a deck so your mixes maintain a consistent volume. Mixxx reads existing ReplayGain tags and analyzes songs that don't have them." %}
gain -> loudness  (even though that's not technically true, it's a more widely-understandable term)

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> +        {% trans "Whether you're dropping thick reggae vocals over some dub, giving shoutouts on the air, or throwing a rap battle, integrate live input from microphones into your mix." %}
live input -> live audio

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> -      <H2>{% trans "Full Feature List" %}</H2>
We should have at least *some* bullet points.  I agree the existing list is excessive but it helps to show that mixxx isn't just another half-ass open source project

2017-02-06 20:05 UTC, ywwg commented on pages/features.html
> -          <p><b>{% blocktrans %}Community Supported<br>Controllers{% endblocktrans %}</b></p>
the number one question people have is "is my controller supported."  We need to have that information very easy to locate.  Maybe a direct link to a page on the wiki?

2017-02-06 20:31 UTC, Be-ing commented on pages/features.html
> +      {% trans "Use reverb, echo, flange, and more effects to blend music in your own signature ways. Assign a Quick Effect to your controller's filter knob to add color to your sound instantly.  Bad
How about:
"Use reverb, echo, flange, and more effects to blend music in your own signature ways _or add spice to your mix_."

2017-02-06 20:33 UTC, Be-ing commented on pages/features.html
> +    {% trans "Free as in freedom as well as price, Mixxx plays nice with a variety of hardware without artificial restrictions or vendor lock-in mechanisms. The free version is the full version. Pick
I like that, but I'd keep "lock-in" instead of "tie-in".

2017-02-06 20:37 UTC, Be-ing commented on pages/features.html
> +        {% trans "Filter your collection by specific tags to narrow your choices or just start typing to find the track you're thinking of. Sort the library table hierarchically with multiple tags at
Thanks for pointing that out. It's just a bad habit of mine. :P

2017-02-06 20:37 UTC, Be-ing commented on pages/features.html
> +        <p>{% trans "Three exclusive designer skins with configurable layouts" %}</p>
Good idea. It [likely will](https://github.com/mixxxdj/mixxx/pull/1151) for 2.1.

2017-02-06 20:40 UTC, Be-ing commented on pages/features.html
> +        {% trans "Whether you're dropping thick reggae vocals over some dub, giving shoutouts on the air, or throwing a rap battle, integrate live input from microphones into your mix." %}
How about "live audio input"?

2017-02-06 20:43 UTC, Be-ing commented on pages/features.html
> +      {% trans "Stay organized and find the music you're looking for the moment you need it. Powered by a high-performance database, navigation and searching your collection is intuitive and fast." %
I'll try figuring out another way to include that sentiment with different wording.

2017-02-06 20:46 UTC, Be-ing commented on pages/features.html
> +      {% trans "Choose between multiple audiophile filters with adjustable EQ shelves. Crossfader curve control lets you deliver quick cuts or long, smooth crossfades." %}
Looking at this again, I'd like to remove the word "audiophile". It comes with baggage. To some DJs, "audiophile" has a connotation with spending $1000 on gold cables for no reason, and I think conflating Mixxx with that could turn some people off.

2017-02-06 20:56 UTC, Be-ing commented on pages/features.html
> +      {% trans "Use reverb, echo, flange, and more effects to blend music in your own signature ways. Assign a Quick Effect to your controller's filter knob to add color to your sound instantly.  Bad
Speaking of effects, could you update the VCI-400 mapping for the new effects UI? There is some [documentation](http://mixxx.org/wiki/doku.php/updating_controller_mappings) for updating mappings on the wiki.

2017-02-06 21:07 UTC, Be-ing commented on pages/features.html
> +      {% trans "Need to extend your mix while you bring in the next track? Loop a 4, 8, or 16 beat segment with ease." %}
I'll put "instantly" back, but some controllers use an encoder push instead of a button to set a loop.

2017-02-06 21:12 UTC, Be-ing commented on pages/features.html
> +        {% blocktrans with hardware_compatibility_wiki_link="/wiki/doku.php/hardware_compatibility" %}<b>Included Presets</b><br> for controllers such as the Traktor Kontrol S4 MK2, Pioneer DDJ-SB &a
That would imply that all the controllers listed on the wiki are fully supported. As much as that has improved recently, it's not true for a lot of older controllers.

2017-02-06 21:14 UTC, Be-ing commented on pages/features.html
> -      <H2>{% trans "Full Feature List" %}</H2>
I think everything on the page above this makes a bullet list redundant.

2017-02-08 05:55 UTC, Be-ing commented
I'll get back to work on this when 2.1 beta is released, but until then, I'll be focusing on finishing things for 2.1.

2017-05-01 17:29 UTC, Be-ing commented
@ywwg could you take another look?

2017-05-01 17:59 UTC, ywwg commented
thanks for working on this more, I'll take a look soon!

2017-05-03 15:27 UTC, ywwg requested changes
looks good! Just a couple small notes

2017-05-03 15:27 UTC, ywwg commented on pages/features.html
> +      {% trans "Compatabile with music files in lossless FLAC, WAV, and AIFF formats as well as lossy MP3, M4A/AAC, Ogg Vorbis, and Opus formats." %}
compatible

2017-05-03 15:27 UTC, ywwg commented on pages/features.html
> +      {% trans "Link up to three effects in a chain for a unique twist on your mix. Fine tune your sound by tweaking each parameter individually. Customize your workflow by assigning different parame
assigning different parameters to tune with the effect's metaknob

2017-05-03 16:17 UTC, Be-ing commented on pages/features.html
> +      {% trans "Link up to three effects in a chain for a unique twist on your mix. Fine tune your sound by tweaking each parameter individually. Customize your workflow by assigning different parame
"tune" is used in the previous sentence. I'll use "adjust".

2017-05-03 16:38 UTC, ywwg approved these changes
thanks for bearing with me, I like it better now :)

2017-05-03 16:58 UTC, Be-ing commented
Thanks for review. I'd like to get the content changes in this and #8 merged, then work on a responsive design.

2017-05-04 02:47 UTC, rryan commented on pages/features.html
> +      {% trans "Play with rhythm by triggering short loops and reverse-playback effects. The track stays in time so you don't miss a beat." %}<!--TODO: Write a better way of explaining slip mode.-->
nit: best to use jinja comments instead of HTML so that it doesn't end up in the final HTML, e.g. 

`{# comment #}`

2017-05-24 19:28 UTC, Be-ing commented
Ready for merge?

2018-04-15 07:12 UTC, Be-ing commented
Ready for merge?

2018-04-16 03:37 UTC, merged