New post about GSoC
mixxxdj/website pull request #102
Opened 2020-06-08 15:26 UTC by crisclacerda

2020-06-08 15:29 UTC, Be-ing commented
add to whitelist

2020-06-08 15:31 UTC, ronso0 requested changes

2020-06-08 15:31 UTC, ronso0 commented on pages/news/2020-06-08-mixxx-GSoC-Coding-Begins.html
> +After one month of community bond period, last week they started coding. Cristiano and Harshit, that are working towards the same end feature, a new beatgrid format capable of handling not only beats
```suggestion
After one month of community bond period, last week they started coding. Cristiano and Harshit, who are both working towards the same final feature, a new beatgrid format capable of handling not only beats, but also downbeats, phrases and sections as well varying tempos and time signatures have already opened a Pull Request each on our main repository. [#2844](https://github.com/mixxxdj/mixxx/pull/2844), [#2847](https://github.com/mixxxdj/mixxx/pull/)
```

2020-06-08 15:31 UTC, ronso0 commented on pages/news/2020-06-08-mixxx-GSoC-Coding-Begins.html
> +Cristiano which is focosing his work on the auto detection of such features is making weekly vlogs on youtube to share his progress with the community. The first one is available here:
```suggestion
Cristiano which is focusing his work on the auto detection of such features is making weekly vlogs on youtube to share his progress with the community. The first one is available here:
```

2020-06-08 15:31 UTC, ronso0 commented on pages/news/2020-06-08-mixxx-GSoC-Coding-Begins.html
> +Janek, which is working on a feature similar to serato flip, had the great idea and prepered a community call, where the new members and (old members alike) had the opportunity to get to know each ot
```suggestion
Janek, who is working on a feature similar to serato flip, had the great idea and prepered a community call, where the new old members alike had the opportunity to get to know each other better and put some faces to their usernames. 
```

2020-06-08 15:31 UTC, ronso0 commented on pages/news/2020-06-08-mixxx-GSoC-Coding-Begins.html
> +{% endblock %}
```suggestion
{% endblock %}

```

2020-06-08 17:24 UTC, Holzhaus requested changes

2020-06-08 17:24 UTC, Holzhaus commented on pages/news/2020-06-08-mixxx-GSoC-Coding-Begins.html
> +<iframe width="560" height="315" src="https://www.youtube.com/embed/rVJ7pBWHp8E" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></ifra
```suggestion
{% include "video.html" with video_id="rVJ7pBWHp8E" %}
```

2020-06-09 01:17 UTC, crisclacerda commented
Used new video tag, but apparently video has no sound, and controls does not appear.

2020-06-09 10:27 UTC, Holzhaus requested changes
Thank you for writing this! If you want you can also add some author metadata for yourself here: https://github.com/mixxxdj/website/blob/website/plugins/news.py#L13-L37

2020-06-09 10:27 UTC, Holzhaus commented on pages/news/2020-06-08-mixxx-GSoC-Coding-Begins.html
> +Stay tuned on [Zulip](https://mixxx.zulipchat.com/)
```suggestion
We are looking forward to a new call in which we discuss our GSoC projects with our students, mentors and the rest of the community.
If you're interested, hit us up on [Zulip](https://mixxx.zulipchat.com/).
```

2020-06-09 10:27 UTC, Holzhaus commented on pages/news/2020-06-08-mixxx-GSoC-Coding-Begins.html
> +Janek, who is working on a feature similar to serato flip, had the great idea and prepered a community call, where the new and old members alike had the opportunity to get to know each other better a
```suggestion
Janek, who is working on [a feature similar to Serato Flip](https://www.mixxx.org/wiki/doku.php/mixxx_macros), had the great idea and prepared a community call where the new and old members alike had the opportunity to get to know each other better and put some faces to their usernames. 
```

2020-06-09 10:27 UTC, Holzhaus commented on pages/news/2020-06-08-mixxx-GSoC-Coding-Begins.html
> +Cristiano which is focusing his work on the auto detection of such features is making weekly vlogs on youtube to share his progress with the community. The first one is available here:
```suggestion
Cristiano which is focusing his work on the auto detection of such features is making weekly vlogs on YouTube to share his progress with the community. The first one is available here:
```

2020-06-09 10:27 UTC, Holzhaus commented on pages/news/2020-06-08-mixxx-GSoC-Coding-Begins.html
> +This year Mixxx is again taking part on Google Summer of Code, and have 3 students working full-time during 3 months to make Mixxx even more awesome.
```suggestion
This year Mixxx is again [taking part in Google Summer of Code]({% url "/news/2020-05-05-mixxx-gsoc-projects-2020.html" %}), and 3 students are working full-time for 3 months to make Mixxx even more awesome.
```

2020-06-09 10:27 UTC, Holzhaus commented on pages/news/2020-06-08-mixxx-GSoC-Coding-Begins.html
> +After one month of community bond period, last week they started coding. Cristiano and Harshit, who are both working towards the same final feature, a new beatgrid format capable of handling not only
```suggestion
After one month of community bonding period, they started coding last week. Cristiano and Harshit, who are both working towards the same final feature—new beatgrid format capable of handling not only beats, but also downbeats, phrases and sections as well varying tempos and time signatures—have already sent some inital patches to Mixxx' Git repository ([#2844](https://github.com/mixxxdj/mixxx/pull/2844), [#2847](https://github.com/mixxxdj/mixxx/pull/2847)).
```

2020-06-09 10:27 UTC, Holzhaus commented
> Used new video tag, but apparently video has no sound, and controls does not appear.

Should be fixed in #103.

2020-06-09 12:23 UTC, crisclacerda commented
> Thank you for writing this! If you want you can also add some author metadata for yourself here: https://github.com/mixxxdj/website/blob/website/plugins/news.py#L13-L37

My pleasure, it's nice to contribute to the website as well. Thanks for the opportunity and for the video tag! 
Next time will be more careful with orthography, barely write English without a text speller, and don't have it on a text editor.
Should be all good now

2020-06-09 17:48 UTC, Holzhaus requested changes

2020-06-09 17:48 UTC, Holzhaus commented on pages/news/2020-06-08-mixxx-GSoC-Coding-Begins.html
> +After one month of community bonding period, they started coding last week. Cristiano and Harshit, who are both working towards the same final feature—new beatgrid format capable of handling not only
Sorry, looks like I missed a word :smile: 

```suggestion
After one month of community bonding period, they started coding last week. Cristiano and Harshit, who are both working towards the same final feature—a new beatgrid format capable of handling not only beats, but also downbeats, phrases and sections as well varying tempos and time signatures—have already sent some inital patches to Mixxx' Git repository ([#2844](https://github.com/mixxxdj/mixxx/pull/2844), [#2847](https://github.com/mixxxdj/mixxx/pull/2847)).
```

2020-06-09 18:59 UTC, Holzhaus commented
Thank you!

2020-06-09 18:59 UTC, merged