Outreachy post
mixxxdj/website pull request #151
Opened 2020-09-23 03:47 UTC by ywwg

2020-09-23 03:48 UTC, ywwg commented on plugins/news.py
> +        'name': 'Owen Williams',
I am not a celebrity :P

2020-09-23 10:12 UTC, daschuer commented
Thank you. I think that can make use of a paragraph how much of the donated money will reach the participant. 
Hopfully we can clarify the situations for Germany and other countries as well. I am waiting for responses to my questions.

2020-09-27 00:42 UTC, ywwg commented
> Thank you. I think that can make use of a paragraph how much of the donated money will reach the participant.

I replied with a general statement because the exact amounts will vary depending on how they donate.  Is that sufficient?

2020-09-27 01:56 UTC, daschuer commented
The 5 % For OpenCollective + 5 % for the fiscal host are constant. Than we should add a warning that a trans-fair via an non US bank is exorbitant expensive and should not be used. The PayPal fee is known. 
And we need to add a warning that PayPal charges silently + %5 due to the currency conversion.  
We should also state that the donation is not Tax deductible.

2020-09-27 03:11 UTC, ywwg commented
clarified values.  I don't want to list every single number because it will be different for everyone.  And rather than say "don't use paypal" I'd prefer to say "try to use a bank transfer"

2020-09-27 06:39 UTC, daschuer commented
From Germany PayPal is the only option.
In my case my Bank charges 8 € + 0.5% 
The credit card was resected.
In addition the website open collective website is broken for bank transfer. See above.

2020-09-27 06:45 UTC, daschuer commented
What exactly was the benefit of opencollective?
We can't make use of Tax deduction from anywhere?
Did you consider to move to betterplace.me?
This is cheaper and transferring the money to outreachy only costs 8€ + 0.5% one time.

2020-09-27 13:41 UTC, ywwg commented
Outreachy recommended opencollective specifically.  I don't know German and I'm in the US, so I can't use a non-US fundraising system.  As I said before, if you want to do the work to run a parallel European fundraiser that is fine with me. 

I don't believe we should be spending this time optimizing for the lowest collection fee when the internship application period starts on thursday.  Opencollective is giving me the support I need and has worked with Outreachy.  They are a good organization and I am comfortable with supporting them.

2020-09-27 15:12 UTC, daschuer commented
> clarified values. I don't want to list every single number because it will be different for everyone. And rather than say "don't use paypal" I'd prefer to say "try to use a bank transfer"

Did you forget to push? 

I think we need a sentence like: use bank transfer from US if possible. Use PayPal from other countries, but be aware of the extra 5% change due to currency conversion.

2020-09-27 19:59 UTC, ywwg commented
oh yeah pushed to the wrong repo

2020-09-27 20:26 UTC, ronso0 commented on pages/news/2020-09-23-outreachy.html
> +We have vetted these organizations and they providing a great service to open source projects like ours, so we are confident that this portion of the money is going to a good place.
```suggestion
We have vetted these organizations and they are providing a great service to open source projects like ours, so we are confident that this portion of the money is going to a good place.
```

2020-09-27 20:31 UTC, daschuer commented on pages/news/2020-09-23-outreachy.html
> +For now, the most efficient way to donate is with a direct bank transfer.
```suggestion
For now, the most efficient way to donate from the U.S. is with a direct bank transfer.
```

2020-09-27 20:44 UTC, daschuer requested changes

2020-09-27 20:44 UTC, daschuer commented on pages/news/2020-09-23-outreachy.html
> +There are additional charges for Paypal or credit card processing and, if applicable, foreign transactions.
```suggestion
The only option for donaing from foreign countries is using PalyPal. PayPal silently adds 5% fee on top of the donated amount if currency conversion is required.   
```

2020-09-27 22:27 UTC, ywwg commented
incorporated changes and fixed a couple typos

2020-09-28 05:36 UTC, daschuer approved these changes
LGTM, thank you.

2020-09-28 15:54 UTC, ywwg commented
Does our system have draft support? i.e. can we merge now and it will go live on the 1st?  Or do we need to wait

2020-10-01 14:01 UTC, merged