GSoC 2024 news
mixxxdj/website pull request #340
Opened 2024-02-27 07:21 UTC by daschuer

2024-02-27 13:50 UTC, ronso0 requested changes

2024-02-27 13:50 UTC, ronso0 commented on content/news/xxxx-xx-xx-mixxx-accepted-for-gsoc-2024.md
> +How Does GSoC Work?
Let's use headers.

`### How Does GSoC Work?`
or
`#### How Does GSoC Work?`

2024-02-27 18:49 UTC, daschuer commented
Done

2024-02-29 00:53 UTC, ronso0 commented
We have the same situation like with the waveforms post: the first header appears in the teaser.
![image](https://github.com/mixxxdj/website/assets/5934199/4f284026-043b-4698-b7e6-87a454ff81bb)

We could move (and modify) the "You could also help us, even if.." paragraph up so the header is not shown.
Or we could ignore it :man_shrugging: 
Or someone knows from the top of his head where to adjust the teaser line treshold (or whatever it's called) to chop headers (and following lines)

Given we want to get this out soonish I'll wait for tomorrow afternoon (~14hours from now), then merge if there are no objections.
Note I didn't do an intense proof-read. LGTM

2024-02-29 07:11 UTC, daschuer commented
I have discovered the "summary" field that solves our headaches with the headers.

2024-02-29 07:12 UTC, daschuer commented
![grafik](https://github.com/mixxxdj/website/assets/1777442/d140c535-be4f-4569-ab6f-fb9a8732d356)

2024-02-29 10:16 UTC, ronso0 commented
> I have discovered the "summary" field that solves our headaches with the headers.

Great! Where can we add that info for authors?

2024-02-29 12:34 UTC, ronso0 commented
Okay, I'll merge this now. Thank you for taking care!

2024-02-29 12:35 UTC, merged