Replace social media widgets with social media links
mixxxdj/website pull request #46
Opened 2018-10-15 04:18 UTC by radusuciu

Removing social media widgets which are dynamically loaded has two main benefits:
- faster page loads
- better for privacy

The main difference is instead of clicking "Tweet" and being invited to tweet, you are linked to the Mixxx Twitter page. In my opinion this is likely to increase engagement with Mixxx's social media. Would be nice if there was some data on how much use the widgets are getting.

The social media links in this PR are styled very similar to the widgets. Also removed jQuery as the only uses of Javascript on the website were simple enough to express without jQuery. It can always be added when needed.

2019-03-01 23:15 UTC, ronso0 commented
I just now became really aware of the website repo..

I wanted to have a quick look at the icons (maybe apply Mixxx style?) but noticed the svgs are inline. does it have any benefit? do you mind storing the icons in separate files so they're easier to review and edit?

2019-03-01 23:22 UTC, ronso0 commented
okay, got it up & running.
before I never was aware of those buttons as my browser blocks fb items..
it's nice to get rid of tracking objects and just link to the social sites instead!

as I thought in the first place, we could omit the text and just use icons.
Without text the buttons would also be small enough to fit underneath **Manual**, next to **Press**. This would make the site look a bit tidier than now.

2019-03-15 03:50 UTC, radusuciu commented
Svg as files would provide a minor benefit through caching I suppose, but it may be balanced out by increased number of requests (unless on HTTP2) - I think. I don't recall exactly but I think I just did it because it was easier.. can of course convert to files

2019-08-23 15:24 UTC, Be-ing commented
I just remembered about this PR. Thank you for reducing external dependencies and getting rid of the tracking. I noticed that the icons can overlap the "DJ Your Way" text:
![image](https://user-images.githubusercontent.com/9455094/63603735-d2d9e000-c58f-11e9-9934-82cabef7a84c.png)
How about getting rid of the "Twitter" and "Facebook" text and just using their icons?

2019-08-23 15:27 UTC, Be-ing commented
Also thanks for adding the Zulip button :+1:

2019-08-23 15:27 UTC, ronso0 commented
yeah, that's pretty much what I proposed above and that would help in narrow view, too
> Without text the buttons would also be small enough to fit underneath Manual, next to Press. This would make the site look a bit tidier than now.

@radusuciu Are able to finish this or should someelse take over?

2019-08-23 15:32 UTC, Be-ing requested changes

2019-08-23 15:32 UTC, Be-ing commented on static/js/mixxx.js
> +  if (navigator.appVersion.indexOf("Win")!=-1) OSName="Windows";
Let's use the same style we use for JS in controller mappings:
```suggestion
  if (navigator.appVersion.indexOf("Win") != -1) {
    OSName="Windows";
  }
```

2019-08-23 15:33 UTC, ronso0 commented
yeah, that's pretty much what I proposed above and that would help in narrow view, too
> Without text the buttons would also be small enough to fit underneath Manual, next to Press. This would make the site look a bit tidier than now.

@radusuciu Are able to finish this or should someelse take over?

2019-08-23 16:47 UTC, radusuciu commented
@ronso0 @Be-ing I can take into account above suggestions and amend the PR!

2019-08-24 22:47 UTC, radusuciu commented
Reverted a commit that added these new side link icons to all pages, as some pages already had elements in the same position, and I think that that would warrant a separate PR.

2019-08-24 23:06 UTC, radusuciu commented
Other changes:
- moved inline svg to separate files
- re-organized js a bit. Namespaced what few functions there are and extracted some js from the download page to it's only file

2019-09-10 11:10 UTC, ronso0 commented
Looks good on desktop and mobile view, works as expected.
Are there any corner cases to test?

2019-09-10 19:18 UTC, radusuciu commented
> Looks good on desktop and mobile view, works as expected.
> Are there any corner cases to test?

Not that I can think of other than trying at different screen sizes.

2019-10-05 20:21 UTC, merged

2019-10-05 20:21 UTC, Be-ing commented
Thanks for taking care of this.